server:
  port: 8089

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true           # <--- ESTO ES VITAL
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1

        - id: account-servce
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=1

        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credits/**
          filters:
            - StripPrefix=1

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Requerimiento: Manejo de trazas con Logback
logging:
  level:
    root: DEBUG
    com.nttdata.bank: DEBUG # Nivel adecuado para ver tus trazas
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
