server:
  port: 8084

spring:
  application:
    name: credit-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_credit 

# Requerimiento: Manejo de trazas con Logback
logging:
  level:
    root: INFO
    com.nttdata.bank: DEBUG # Nivel adecuado para ver tus trazas

transaction:
  service:
    url: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true