server:
  port: 8082 

spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_customers 

# Requerimiento: Manejo de trazas con Logback
logging:
  level:
    root: INFO
    com.nttdata.bank: DEBUG # Nivel adecuado para ver tus trazas

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true    

gatewey:
  service:
    url: http://localhost:8080

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      creditService:
        timeout-duration: 2s  
  timelimiter:
    instances:
      accountService:
        timeoutDuration: 2s
