server:
  port: 8082 
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_customers 

# Requerimiento: Manejo de trazas con Logback
logging:
  level:
    root: INFO
    com.nttdata.bank: DEBUG # Nivel adecuado para ver tus trazas