server:
  port: 8083

spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_transaction 

# Requerimiento: Manejo de trazas con Logback
logging:
  level:
    root: INFO
    com.nttdata.bank: DEBUG # Nivel adecuado para ver tus trazas

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true    